# Generated by Django 2.2.4 on 2022-05-07 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion
from datetime import timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Disease_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Disease_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('problem', models.TextField(max_length=2000)),
                ('symtoms', models.TextField(max_length=2000)),
                ('speed', models.CharField(max_length=200)),
                ('precautions', models.TextField(max_length=2000)),
                ('image', models.FileField(upload_to='documents/', verbose_name='Image')),
                ('link', models.CharField(max_length=2000, null=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=30, null=True)),
                ('doc_license_no', models.CharField(max_length=30, null=True, unique=True)),
                ('hospital_license_no', models.CharField(max_length=30, null=True, unique=True)),
                ('doc_license_expire_date', models.DateField(max_length=30, null=True)),
                ('hospital_license_expire_date', models.DateField(max_length=30, null=True)),
                ('country', models.CharField(max_length=30, null=True)),
                ('state', models.CharField(max_length=30, null=True)),
                ('city', models.CharField(max_length=30, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('hospital_address', models.CharField(max_length=200, null=True)),
                ('doctor_type', models.CharField(choices=[('', 'Select'), ('govt', 'Govt Doctor'), ('pvt', 'Private Doctor')], default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=40, unique=True)),
                ('doctor_name', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('doc_license_no', models.CharField(max_length=30, unique=True)),
                ('hospital_license_no', models.CharField(max_length=30, unique=True)),
                ('degree', models.CharField(max_length=30, null=True)),
                ('specialist', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('hospital_address', models.CharField(max_length=200)),
                ('doctor_type', models.CharField(choices=[('', 'Select'), ('govt', 'Govt Doctor'), ('pvt', 'Private Doctor')], default='', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(blank=True, default='79415', editable=False, max_length=10, unique=True)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField(max_length=2000)),
                ('image', models.FileField(upload_to='documents/', verbose_name='Patient Image')),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer_Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Visiting_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visiting_hour_weekdays', models.CharField(max_length=30)),
                ('visiting_hour_weekend', models.CharField(max_length=30)),
                ('visiting_hour_online_weekdays', models.CharField(max_length=30)),
                ('visiting_hour_online_weekend', models.CharField(max_length=30)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor_Register')),
            ],
        ),
        migrations.CreateModel(
            name='Unauthorised_Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('problem', models.TextField(max_length=2000)),
                ('symtoms', models.TextField(max_length=2000)),
                ('precautions', models.TextField(max_length=2000)),
                ('date', models.DateField(default=datetime.datetime(2022, 5, 7, 13, 28, 43, 811061, tzinfo=timezone.utc), verbose_name='Posted Date')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor_Register')),
            ],
        ),
        migrations.CreateModel(
            name='Report_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200)),
                ('problem', models.TextField(max_length=200)),
                ('report', models.FileField(upload_to='documents/', verbose_name='Report')),
                ('visiting_date', models.DateField()),
                ('follow_up_date', models.DateField()),
                ('prescription', models.FileField(upload_to='documents/', verbose_name='Prescription')),
                ('Pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient_Detail')),
                ('doctor_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Doctor_Register')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer_Detail')),
            ],
        ),
        migrations.CreateModel(
            name='Disease_Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('count', models.IntegerField(null=True, verbose_name='No of Affected Count')),
                ('cured_count', models.IntegerField(null=True, verbose_name='Cured Count')),
                ('current_count', models.IntegerField(null=True, verbose_name='No of Currently Affected Count')),
                ('disease_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Disease_Category')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor_Register')),
            ],
        ),
        migrations.CreateModel(
            name='Disease_Spread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=200)),
                ('count', models.IntegerField(null=True, verbose_name='No of Affected Count')),
                ('cured_count', models.IntegerField(null=True, verbose_name='Cured Count')),
                ('current_count', models.IntegerField(null=True, verbose_name='No of Currently Affected Count')),
                ('date', models.DateField()),
                ('disease_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Disease_Category')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=30)),
                ('problem', models.CharField(max_length=200)),
                ('visiting_date', models.DateField(max_length=30)),
                ('visiting_time', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Customer_Detail')),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor_Register')),
            ],
        ),
    ]
