# Generated by Django 2.2.4 on 2022-05-09 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=40, unique=True)),
                ('mail', models.EmailField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('hospital_license_no', models.CharField(max_length=30, unique=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('hospital_address', models.CharField(max_length=200)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Area')),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hospital_id',
        ),
        migrations.DeleteModel(
            name='Disease_Detail',
        ),
        migrations.RemoveField(
            model_name='disease_spread',
            name='disease_name',
        ),
        migrations.RemoveField(
            model_name='disease_update',
            name='disease_name',
        ),
        migrations.RemoveField(
            model_name='disease_update',
            name='doctor_id',
        ),
        migrations.DeleteModel(
            name='Doctor_Detail',
        ),
        migrations.RemoveField(
            model_name='patient_detail',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='report_detail',
            name='Pid',
        ),
        migrations.RemoveField(
            model_name='report_detail',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='report_detail',
            name='patient_id',
        ),
        migrations.RemoveField(
            model_name='unauthorised_disease',
            name='doctor_id',
        ),
        migrations.RemoveField(
            model_name='visiting_detail',
            name='hospital_id',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Disease_Category',
        ),
        migrations.DeleteModel(
            name='Disease_Spread',
        ),
        migrations.DeleteModel(
            name='Disease_Update',
        ),
        migrations.DeleteModel(
            name='Doctor_Register',
        ),
        migrations.DeleteModel(
            name='Patient_Detail',
        ),
        migrations.DeleteModel(
            name='Report_Detail',
        ),
        migrations.DeleteModel(
            name='Unauthorised_Disease',
        ),
        migrations.DeleteModel(
            name='Visiting_Detail',
        ),
    ]
