# Generated by Django 2.2.4 on 2022-05-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220509_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_register',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('Approved', 'Approve'), ('Rejected', 'Reject')], max_length=200, null=True),
        ),
    ]
