# Generated by Django 2.2.4 on 2022-05-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_hospital_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_register',
            name='image',
            field=models.FileField(null=True, upload_to='documents/', verbose_name='Upload Image'),
        ),
    ]
