# Generated by Django 2.2.4 on 2022-05-18 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_hospital_register_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_detail', models.TextField(max_length=2000)),
                ('bed_detail', models.TextField(max_length=2000)),
                ('blood_bank', models.TextField(max_length=2000)),
                ('medical_detail', models.TextField(max_length=2000)),
                ('ambulance', models.TextField(max_length=2000)),
                ('other', models.TextField(max_length=2000)),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Hospital_Register')),
            ],
        ),
    ]
