# Generated by Django 2.2.4 on 2022-05-18 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_register',
            name='specialist',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
