# Generated by Django 2.2.4 on 2022-05-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_hospital_register_specialist'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilities',
            name='cylinder_count',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
