# Generated by Django 2.2.4 on 2022-05-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_facilities_cylinder_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilities',
            name='bed_detail',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='cylinder_count',
            field=models.IntegerField(null=True),
        ),
    ]
